# Dijkstra Algorithm

$S=\emptyset$  
$\bar{S}=N$  
$d(i)=\infty, \forall i \in N$  
$d(s)=0$  
while $\bar{S}=\emptyset:$  
$\:\:\:\:$ $pick \: i \in \bar{S} \: st. \: d(i)=min\{d(j): j \in \bar{S}\}$  
$\:\:\:\:$ $S=S\cup\{i\}$  
$\:\:\:\:$ $S=S\setminus\{i\}$  
$\:\:\:\:$ $for \: each \: arc \: (i,j) \in A(i):$  
$\:\:\:\:\:\:\:\:$ $if \: d(j)>d(i)+c_{ij}:$  
$\:\:\:\:\:\:\:\:\:\:\:\:$ $d(j)=d(i)+c_{ij}$  
$\:\:\:\:\:\:\:\:\:\:\:\:$ $pred(j)=i$

# Libraries

In [2]:
from sys import maxsize
import pandas as pd

# Parameters

In [3]:
M = None

#           9   11  12  13  14  15  16  17   
graph = [[  0,  18, M,  30, M,  M,  M,  M ],    # 9
         [  M,  0,  M,  M,  M,  M,  M,  M ],    # 11
         [  M,  0,  0,  M,  M,  21, M,  38],    # 12
         [  M,  M,  0,  0,  M,  M,  22, M ],    # 13
         [  M,  M,  M,  0,  0,  M,  M,  20],    # 14
         [  M,  M,  M,  M,  0,  0,  M,  M ],    # 15
         [  M,  M,  M,  M,  M,  0,  0,  9 ],    # 16
         [  M,  M,  M,  M,  M,  M,  M,  0 ]]    # 17

nodes = [9, 11, 12, 13, 14, 15, 16, 17]

network_df = pd.DataFrame(graph, columns=nodes)
network_df.index = nodes

In [4]:
network_df

     9     11   12    13   14    15    16    17
9   0.0  18.0  NaN  30.0  NaN   NaN   NaN   NaN
11  NaN   0.0  NaN   NaN  NaN   NaN   NaN   NaN
12  NaN   0.0  0.0   NaN  NaN  21.0   NaN  38.0
13  NaN   NaN  0.0   0.0  NaN   NaN  22.0   NaN
14  NaN   NaN  NaN   0.0  0.0   NaN   NaN  20.0
15  NaN   NaN  NaN   NaN  0.0   0.0   NaN   NaN
16  NaN   NaN  NaN   NaN  NaN   0.0   0.0   9.0
17  NaN   NaN  NaN   NaN  NaN   NaN   NaN   0.0

# The Function Definitons

In [56]:
# Functions to print the latest obtained path

def intersperse(lst, item):
    result = [item] * (len(lst) * 2 - 1)
    result[0::2] = lst
    return result

def print_path(pred, start, end, cost):
    l = [end]
    l.append(pred[end])
    while start not in l:
        l.append(pred[l[-1]])
    
    l.reverse()
    path_string = intersperse(list(map(str, l)), " -> ")
    print("The shortest path from {} to {} is ".format(start, end) + "".join(path_string) + " with the cost {}.".format(cost))

In [59]:
# The Dijkstra function 

def dijkstra(network, start, end):
    # network (pandas.core.frame.DataFrame): The matrix including the cost information of the network
    # start (int): The index name of the source node
    # end (int): The index name of the sink node
    nodes = list(network.index) # Creating a list for the index names of the nodes
    n = len(network) # Number of nodes
    S = [] # The permanent set
    S_bar = nodes # The temporary set
    d = dict(map(lambda i,j : (i,j) , nodes, n*[maxsize])) # d(i), pins the shortest path distance
    d[start] = 0 # d(i) initially has 0 at the source node, and infinity at the any other node
    pred = {} # pred, records the actual shortest path
    iter = 0 # Iteration variable

    while len(S_bar) > 0:
        # Report
        print("Iteration {}".format(iter))
        print("Permanent Set:")
        print(S)
        print("Temporary Set:")
        print(S_bar)
        print("d:")
        print({key: None if value == maxsize else value for (key, value) in d.items()})
        print("\n")

        # Function body
        i = min({key: d[key] for key in S_bar}, key=d.get) # Pick the key with the minimum value in the temporary set
        S.append(i) # Add i to the permanent set
        S_bar.remove(i) # Remove i from the temporary set

        adj_list = network.loc[i].loc[network.columns != i].dropna() # Arcs emanating from i, and their costs
        for j, c in zip(list(adj_list.index), list(adj_list.values)): # For each arc emanating from i:
            if d[j] > d[i] + c: # Update d if necessary
                d[j] = d[i] + c
                pred[j] = i # Update the path

        iter += 1 # Update the iteration variable

    cost = d[end] # Record the cost of the shortest path
    print_path(pred, start, end, cost)

    return None

In [60]:
dijkstra(network_df, 9, 17)

Iteration 0
Permanent Set:
[]
Temporary Set:
[9, 11, 12, 13, 14, 15, 16, 17]
d:
{9: 0, 11: None, 12: None, 13: None, 14: None, 15: None, 16: None, 17: None}


Iteration 1
Permanent Set:
[9]
Temporary Set:
[11, 12, 13, 14, 15, 16, 17]
d:
{9: 0, 11: 18.0, 12: None, 13: 30.0, 14: None, 15: None, 16: None, 17: None}


Iteration 2
Permanent Set:
[9, 11]
Temporary Set:
[12, 13, 14, 15, 16, 17]
d:
{9: 0, 11: 18.0, 12: None, 13: 30.0, 14: None, 15: None, 16: None, 17: None}


Iteration 3
Permanent Set:
[9, 11, 13]
Temporary Set:
[12, 14, 15, 16, 17]
d:
{9: 0, 11: 18.0, 12: 30.0, 13: 30.0, 14: None, 15: None, 16: 52.0, 17: None}


Iteration 4
Permanent Set:
[9, 11, 13, 12]
Temporary Set:
[14, 15, 16, 17]
d:
{9: 0, 11: 18.0, 12: 30.0, 13: 30.0, 14: None, 15: 51.0, 16: 52.0, 17: 68.0}


Iteration 5
Permanent Set:
[9, 11, 13, 12, 15]
Temporary Set:
[14, 16, 17]
d:
{9: 0, 11: 18.0, 12: 30.0, 13: 30.0, 14: 51.0, 15: 51.0, 16: 52.0, 17: 68.0}


Iteration 6
Permanent Set:
[9, 11, 13, 12, 15, 14]
Temporary Set:
[16, 17]
d:
{9: 0, 11: 18.0, 12: 30.0, 13: 30.0, 14: 51.0, 15: 51.0, 16: 52.0, 17: 68.0}


Iteration 7
Permanent Set:
[9, 11, 13, 12, 15, 14, 16]
Temporary Set:
[17]
d:
{9: 0, 11: 18.0, 12: 30.0, 13: 30.0, 14: 51.0, 15: 51.0, 16: 52.0, 17: 61.0}


The shortest path from 9 to 17 is 9 -> 13 -> 16 -> 17 with the cost 61.0.